### ISSUE TITLE
Chromium Browser in a Singleton

### ISSUE THREAD

**Issue by kurtisane** [microsoft/playwright-sharp#1021]
Hi,
I'm trying to keep the Chromium Browser Object in a Singleton and access this to create a new Page from somewhere else.

So basically I have my BrowserService which is running as a Singleton and holds the ChromiumBrowser Object. This ChromiumBrowser is instantiated when the Constructor of BrowserService runs. So right at the beginning of my application. 

When now using the "BrowserService.ChromiumBrowser.NewPageAsync" this exception is thrown:

`PlaywrightSharp.PlaywrightSharpException: Connection closed
   at PlaywrightSharp.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args, Boolean ignoreNullValues, JsonSerializerOptions options, Boolean treatErrorPropertyAsError) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 218
   at PlaywrightSharp.Browser.NewContextAsync(BrowserContextOptions options) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Browser.cs:line 149
   at PlaywrightSharp.Browser.NewPageAsync(BrowserContextOptions options) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Browser.cs:line 244`

When trying to create a new page in the constructor of BrowserService it works without a issue.
Any idea why ?

**Comment by kblok** [comment]
What's your platform @kurtisane?
ASP.NET Core? Are you using a DI?

**Comment by kurtisane** [comment]
.Net Core 3.1 

And yes I'm using DI.
Adding "BrowserService" as a Singleton.

**Comment by kurtisane** [comment]
Any advice ?

**Comment by kblok** [comment]
I bet that the Playwright class is being disposed at some point during the life cycle of the app.
Does it fail in the first call or after a few minutes? Could you cook a code example?

**Comment by kurtisane** [comment]
That was it. Playwright itself needs to be stored.
