### ISSUE TITLE
LaunchOptions env problem

### ISSUE THREAD

**Issue by thomaschanneladvisor** [microsoft/playwright-sharp#1072]
When i create a env Dictionary<string, string> in LaunchOptions i run into an error when calling LaunchAsnyc with message
_env: expected array, got object_
```
...
   at PlaywrightSharp.Transport.Connection.<SendMessageToServerAsync>d__25`1.MoveNext() in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 144
...
   at PlaywrightSharp.BrowserType.<LaunchAsync>d__15.MoveNext() in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/BrowserType.cs:line 102
```
Looking here https://github.com/microsoft/playwright/blob/master/docs/api.md#browsertypelaunchserveroptions
env and firefoxUserPrefs have the same type in the value position and i have successfully used firefoxUserPrefs , so i am wondering if env should be <string, object> instead of <string, string> ?

**Comment by kblok** [comment]
I think we need to change how we serialize those dictionaries. Thanks for reporting this. I'll take a look at that.

**Comment by thomaschanneladvisor** [comment]
@kblok Thanks for sorting that so quickly, I can confirm working for me after getting the newest nuget repo 🥇
