### ISSUE TITLE
Cannot create Firefox browser - protocol error / Browser closed

### ISSUE THREAD

**Issue by fr4gles** [microsoft/playwright-sharp#1101]
I get an error trying to invoke `LaunchAsync` on Firefox browser on production Windows Server 2019 (machine 1) while it's working fine on developer station Windows 10 Pro (machine 2).
It's working OK with Chromium on Windows Server 2019.

Running `PlaywrightSharp Version="0.170.2"` on `.NET Core 3.1.11`

Simplyfied code:
```
await PlaywrightSharp.Playwright.InstallAsync();

var server = await PlaywrightSharp.Playwright.CreateAsync(new NLogLoggerFactory(new NLogProviderOptions()));

var options = new LaunchOptions()
{
	Headless = true,
	IgnoreHTTPSErrors = true,
	options.Proxy = new ProxySettings() { Server = ... };
};
var browser = await server.Firefox.LaunchAsync(options);

var contextOptions = new BrowserContextOptions();
contextOptions.Locale = "en-US";
contextOptions.Geolocation = new Geolocation { Longitude = 12.492507m, Latitude = 41.889938m };
contextOptions.Permissions = new[] { ContextPermission.Geolocation };
contextOptions.IgnoreHTTPSErrors = true;
var context = await browser.NewContextAsync(contextOptions);
await context.ClearCookiesAsync();

var page = await context.NewPageAsync();
page.DefaultNavigationTimeout = 15000;
page.DefaultTimeout = 15000;
var response = await _page.GoToAsync(..., LifecycleEvent.Load, 15000);
```

Error:
```
PlaywrightSharp.TargetClosedException: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Users\abc\AppData\Local\ms-playwright\firefox-1221\firefox\firefox.exe -no-remote -headless -profile C:\Users\abc\AppData\Local\Temp\playwright_firefoxdev_profile-M08Ucd -juggler-pipe -silent
<launched> pid=52144
[err] *** You are running in headless mode.
[out] 
[out] Juggler listening to the pipe
[out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[err] 
[err] ###!!! [Child][MessageChannel] Error: (msgtype=0x3A0147,name=PContent::Msg_AsyncMessage) Channel closing: too late to send/recv, messages will be lost
[err] 
[err] JavaScript error: resource://activity-stream/lib/ASRouterNewTabHook.jsm, line 61: TypeError: this._router is null
[out] console.error: Region.jsm: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", "chrome://juggler/content/NetworkObserver.js", 421))
[out] console.error: Region.jsm: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.jsm", 376))
<process did exit: exitCode=0, signal=null>
=========================== logs ===========================
<launching> C:\Users\abc\AppData\Local\ms-playwright\firefox-1221\firefox\firefox.exe -no-remote -headless -profile C:\Users\abc\AppData\Local\Temp\playwright_firefoxdev_profile-M08Ucd -juggler-pipe -silent
<launched> pid=52144
[err] *** You are running in headless mode.
[out] 
[out] Juggler listening to the pipe
[out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
[err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
[err] 
[err] ###!!! [Child][MessageChannel] Error: (msgtype=0x3A0147,name=PContent::Msg_AsyncMessage) Channel closing: too late to send/recv, messages will be lost
[err] 
[err] JavaScript error: resource://activity-stream/lib/ASRouterNewTabHook.jsm, line 61: TypeError: this._router is null
[out] console.error: Region.jsm: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", "chrome://juggler/content/NetworkObserver.js", 421))
[out] console.error: Region.jsm: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.jsm", 376))
<process did exit: exitCode=0, signal=null>
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
   at PlaywrightSharp.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args, Boolean ignoreNullValues, JsonSerializerOptions serializerOptions, Boolean treatErrorPropertyAsError) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 163
   at PlaywrightSharp.BrowserType.LaunchAsync(LaunchOptions options) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/BrowserType.cs:line 102
```

machine 1:
```
OS Name             : Microsoft Windows Server 2019 Standard
OS Version          : 10.0.17763 N/A Build 17763
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Server
OS Build Type       : Multiprocessor Free
System Boot Time    : 1/13/2021, 5:06:02 PM
System Manufacturer : Supermicro
System Model        : Super Server
System Type         : x64-based PC
System Directory    : C:\Windows\system32
System Locale       : en-us;English (United States)
```

machine 2:
```
OS Name             : Microsoft Windows 10 Pro
OS Version          : 10.0.19042 N/A Build 19042
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Workstation
OS Build Type       : Multiprocessor Free
System Boot Time    : 2021-01-13, 02:05:39
System Manufacturer : Dell Inc.
System Model        : XPS 15 9560
System Type         : x64-based PC
System Directory    : C:\WINDOWS\system32
System Locale       : pl;Polish
```

**Comment by kblok** [comment]
What do you think about this @aslushnikov?

**Comment by MaxBex** [comment]
Same here after update from v. 0.170.2 to v. 0.180.0 on Windows 10 Pro. If downgrade everything is working normally.

**Comment by kababoom** [comment]
Do you have latest VC++ installed?

**Comment by fr4gles** [comment]
> Do you have latest VC++ installed?

Yes
x64: vc_redist.x64.exe - 14.28.29.3125

**Comment by MaxBex** [comment]
> Do you have latest VC++ installed?

I've the x64 v. 14.28.29325.2.

**Comment by ozcanmirac** [comment]
Getting exact same error. Is there any resolution?

**Comment by MaxBex** [comment]
> Getting exact same error. Is there any resolution?

I've solved by come back at the V. 0.170.2, is working as usual for me.

**Comment by mxschmitt** [comment]
@kblok created an upstream issue to track [it](https://github.com/microsoft/playwright/issues/5355). It seems its already fixed in Firefox (3 days ago) and should be then fixed in Playwright on the next FF roll.

**Comment by ThaDaVos** [comment]
Any fix for this?

**Comment by pavelfeldman** [comment]
Could you give it a try on https://www.nuget.org/packages/Microsoft.Playwright/1.11.1-alpha-2?

**Comment by pavelfeldman** [comment]
Could you please verify that it works in https://www.nuget.org/packages/Microsoft.Playwright/1.12.0-alpha-4 and file an issue + link this one if it does not?

**Comment by fr4gles** [comment]
There are some breaking changes in version `1.x` of `Microsoft.Playwright`, it would take time until we'll upgrade.
I will link this one as suggested if it's still not working.

For now we have partially switched from `playwright/firefox` to `puppeter/chrome` and `playwright/webkit`
