### ISSUE TITLE
Unable to.compile V.0.191.0

### ISSUE THREAD

**Issue by MaxBex** [microsoft/playwright-sharp#1182]
After update from.V.0.170.2 to V.0.191.0 I'm unable to compile the project.

System.IO.DirectoryNotFoundException: the working directory "bin\Debug\net5.0-windows\.playwright\win-x64\native" not exist

**Comment by kblok** [comment]
@MaxBex I see that the output is .NET5.0-windows... I can infer something from there. Could you tell us a little bit more about your projects? type of project, target framework. If you can share some relevant parts of your csproj that would be awesome.

**Comment by Xen0byte** [comment]
I'm getting the same:

```
Error	MSB6003	The specified task executable "cmd.exe" could not be run. System.IO.DirectoryNotFoundException: The working directory "bin\Debug\net5.0\.playwright\win-x64\native" does not exist.
   at Microsoft.Build.Tasks.Exec.GetWorkingDirectory()
   at Microsoft.Build.Utilities.ToolTask.GetProcessStartInfo(String pathToTool, String commandLineCommands, String responseFileSwitch)
   at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
   at Microsoft.Build.Tasks.Exec.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
   at Microsoft.Build.Utilities.ToolTask.Execute()	TestEngine	C:\Users\...\.nuget\packages\playwrightsharp\0.191.0\build\netstandard2.0\PlaywrightSharp.targets
```

Potentially relevant project details:

1.
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>NET5.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="PlaywrightSharp" Version="0.191.0" />
	</ItemGroup>

</Project>
```

2.
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>NET5.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ExcelDataReader" Version="3.7.0-develop00310" />
		<PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0-develop00310" />
		<PackageReference Include="ExtentReports" Version="4.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0-preview.1.21102.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0-preview.1.21102.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.0-preview.1.21102.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0-preview.1.21102.12" />
		<PackageReference Include="PlaywrightSharp" Version="0.191.0" />
		<PackageReference Include="SpecFlow" Version="3.7.13" />
	</ItemGroup>

</Project>
```

3.
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>NET5.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.0-preview.1.21102.2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0-preview-20210219-03" />
		<PackageReference Include="NUnit" Version="3.13.1" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.0.0-beta.1" />
		<PackageReference Include="PlaywrightSharp" Version="0.191.0" />
		<PackageReference Include="SpecFlow" Version="3.7.13" />
		<PackageReference Include="SpecFlow.NUnit" Version="3.7.13" />
		<PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.7.13" />
	</ItemGroup>

</Project>
```

**Comment by kblok** [comment]
I was able to reproduce it

**Comment by kblok** [comment]
v0.191.1 published. Sorry for the hiccup folks.
