### ISSUE TITLE
Protocol error (Network.getResponseBody): Browser closed.

### ISSUE THREAD

**Issue by cirrusone** [microsoft/playwright-sharp#1308]
If I subscribe to the `page.Response` eventhandler I was expecting `await page.GoToAsync` would await all events being completed. However, this is not what I'm seeing and get error 

`PlaywrightSharp.TargetClosedException HResult=0x80131500 Message=Protocol error (Network.getResponseBody): Browser closed.`

I've also added an await for all of the load states `await page.WaitForLoadStateAsync(LifecycleEvent.DOMContentLoaded & LifecycleEvent.Load & LifecycleEvent.Networkidle);` but still get this error.

I can await an arbitrary delay which works okay (`await Task.Delay(5000);`) but would rather await something tangible.

Is there something else I can wait for until all response events have completed before continuing?

Version: PlaywrightSharp v0.180.0

Example Code: 

```
using PlaywrightSharp;
using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WinFormsApp1
{
    public partial class Form1 : Form
    {
        private string _logPath;
        public Form1()
        {
            InitializeComponent();
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            _logPath = Path.Combine(AppContext.BaseDirectory, "Logs");

            if (!Directory.Exists(_logPath))
            {
                Directory.CreateDirectory(_logPath);
            }

            DirectoryInfo di = new DirectoryInfo(_logPath);
            foreach (FileInfo file in di.GetFiles())
            {
                file.Delete();
            }

            // Get resolution of screen where current form resides
            Screen myScreen = Screen.FromControl(this);
            Rectangle workingArea = myScreen.WorkingArea;

            await Task.Run(() => TestPlaywright(workingArea));
        }

        private async Task TestPlaywright(Rectangle workingArea)
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(headless: false);
            var page = await browser.NewPageAsync();
            await page.SetViewportSizeAsync(new ViewportSize() { Height = workingArea.Height - 100, Width = workingArea.Width - 100 });
            page.Response += new EventHandler<ResponseEventArgs>(Page_Response);
            await page.GoToAsync("https://www.bbc.co.uk/news");
            await page.WaitForLoadStateAsync(LifecycleEvent.DOMContentLoaded & LifecycleEvent.Load & LifecycleEvent.Networkidle);
            //await Task.Delay(5000);
        }

        private static async void Page_Response(object sender, ResponseEventArgs e)
        {
            try
            {

                if (e.Response.Status != System.Net.HttpStatusCode.OK)
                {
                    Debug.WriteLine($"Status Error - Status:{e.Response.Status}");
                    return;
                }

                await e.Response.FinishedAsync();
                var responseBytes = await e.Response.GetBodyAsync();
                var responseText = await e.Response.GetTextAsync();

                Debug.WriteLine($"Success - url:{e.Response.Url}");
            }
            catch (Exception ex)
            {
                // log exception
                Debug.WriteLine($"Error - url:{e.Response.Url}");
            }
        }

    }
}
```

Full Error:
```

PlaywrightSharp.TargetClosedException
  HResult=0x80131500
  Message=Protocol error (Network.getResponseBody): Browser closed.
==================== Browser output: ====================
<launching> C:\Users\...\AppData\Local\ms-playwright\chromium-844399\chrome-win\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=C:\Users\...\AppData\Local\Temp\playwright_chromiumdev_profile-5p1PLR --remote-debugging-pipe --no-sandbox --no-startup-window
<launched> pid=6292
<gracefully close start>
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlaywrightSharp.Transport.Connection.<SendMessageToServerAsync>d__23`1.MoveNext() in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 141
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlaywrightSharp.Transport.Channels.ResponseChannel.<GetBodyAsync>d__1.MoveNext() in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Transport/Channels/ResponseChannel.cs:line 13
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlaywrightSharp.Response.<GetBodyAsync>d__25.MoveNext() in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Response.cs:line 84
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WinFormsApp1.Form1.<Page_Response>d__4.MoveNext() in ...\PlaywrightTest\PlaywrightTest Response Event\WinFormsApp1\Form1.cs:line 70
```

**Comment by kblok** [comment]
I will take a look at it @cirrusone

**Comment by pavelfeldman** [comment]
You close the browser before you finished fetching the body, so it looks like working as intended!
