### ISSUE TITLE
Error with playwright-sharp on VPS Ubuntu

### ISSUE THREAD

**Issue by mrgumorist** [microsoft/playwright-sharp#1371]
Hello! Hello! Can someone help me? I use playwright-sharp in my application. I deployed it and sended to vps, launched and got exception as a result. Google could'nt help me, I was trying to find solution. I found that my app working on windows, but I have VPS Ubuntu, where it was hosted.
It's a problem:
`One or more errors occurred. (One or more errors occurred. (Driver not found in any of the locations.))
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Sheduler_bot.Controllers.HomeController.Index() in C:\Users\mrgumorist\source\repos\Sheduler_bot\Sheduler_bot\Controllers\HomeController.cs:line 33
System.Private.CoreLib
System.AggregateException: One or more errors occurred. (Driver not found in any of the locations.)
 ---> PlaywrightSharp.PlaywrightSharpException: Driver not found in any of the locations.
   at PlaywrightSharp.Transport.Connection.GetExecutablePath() in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 270
   at PlaywrightSharp.Transport.Connection.GetProcess(String driverExecutablePath) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 233
   at PlaywrightSharp.Transport.Connection.InstallAsync(String driverPath, String browsersPath) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 115
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Sheduler_bot.Services.GeneralAutomatedService.LoadPlaywright() in C:\Users\mrgumorist\source\repos\Sheduler_bot\Sheduler_bot\Services\GeneralAutomatedService.cs:line 26
Boolean Wait(Int32, System.Threading.CancellationToken)
System.Collections.ListDictionaryInternal
-2146233088`

I don't understand why my local machine path is on the exception. It's hosted on VPS!
My code looks like: 
```
await Playwright.InstallAsync();
            playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new LaunchOptions { Headless = true });
```
I'm using the latest one version.
![image](https://user-images.githubusercontent.com/29434721/118122342-6524b600-b3fb-11eb-83eb-bb6457534b50.png)
I'm publishing on my folder, and then transfer files by ftp and restarting my service by ssh with command.
![image](https://user-images.githubusercontent.com/29434721/118122377-7077e180-b3fb-11eb-9912-3a048dac8197.png)

**Comment by pavelfeldman** [comment]
Please try recent https://www.nuget.org/packages/Microsoft.Playwright/1.11.1-alpha-2. File a new issue if it does not help and link this one.
