### ISSUE TITLE
Playwright.InstallAsync(): Permission denied

### ISSUE THREAD

**Issue by tiny-dancer** [microsoft/playwright-sharp#906]
Recently back into the dotnet space so hopefully an easy fix on my part.  Occurring on local mac osx

```c#
Console.WriteLine("Installing playwright");
await Playwright.InstallAsync();
```

```
System.ComponentModel.Win32Exception: Permission denied

System.ComponentModel.Win32Exception
Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at PlaywrightSharp.Transport.Connection.InstallAsync() in C:\source\personal\playwright-sharp\src\PlaywrightSharp\Transport\Connection.cs:line 67
   at Tests.Integration.UnitTest1.InitializeAsync() in UnitTest1.cs:line 16
   at Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 201
   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 107

```

Thanks!

**Comment by mrgumorist** [comment]
> We just shipped v0.142.0. Could you try that version?

It's doesn't work on my PC.

**Comment by mrgumorist** [comment]
It's crash on Playwright.InstallAsync.

**Comment by kblok** [comment]
@mrgumorist can you share your OS and stack trace?

**Comment by tiny-dancer** [comment]
@kblok confirmed latest release (or coincidentally running it via node first) resolved the issue

**Comment by kblok** [comment]
Awesome!
@mrgumorist would you mind creating a new issue for your case?
